version: '3'

services:
  app:
    container_name: "tibia-core"
    build: .
    command: python main.py
    volumes: 
      - ".:/usr/app"
    depends_on: 
      - db
    links: 
      - db
  db:
    image: "mongo"
    container_name: "tibia-database"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker
      MONGO_INITDB_ROOT_PASSWORD: docker
    ports: 
      - "27017:27017"