version: "3"

services:
  app:
    build: .
    command: HTTPX_LOG_LEVEL=debug python main.py
    depends_on:
      - db
    links:
      - db
    volumes:
      - ".:/usr/app"
  db:
    image: "mongo"
    ports:
      - "27017:27017"
    restart: always
